[package]
name = "rix"
version = "0.1.0"
edition = "2018"

[lib]
name = "rix"
path = "src/lib.rs"

[[bin]]
name = "rix"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "0.12"
predicates = "2"

[dependencies]
clap = "2"
colored = "2"
libc = "0"
nix = "0"
nom = "7"
serde = "1"
serde_json = "1"
tempfile = "3"